resilience4j.circuitbreaker:
  instances:
    avaliacaoCB:
      minimumNumberOfCalls: 4
      slidingWindowSize: 8

management:
  endpoints:
    enabled-by-default: false
    web:
     exposure:
       include: 'health, metrics'
  endpoint:
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true